config/routes.rb
Rails.application.routes.draw do
  get 'images/new'

  get 'photos/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "pages#index"
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
  	resources :postcomments
  end

  resources :photos do
    member do
      get :vote
    end
  end
  resources :images
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :photos
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :user

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/photo.rb
class Photo < ApplicationRecord
	mount_uploader :photo, FotoUploader

	has_many :votes
	
	belongs_to :user
	belongs_to :category
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	 has_many :postcomments
	 
	validates :title, length: { in: 1..20 }
	validates :body, length: { in: 10..5012 }
	validates :title, uniqueness: true
	validates :title, presence: true
	
end

app/models/postcomment.rb
class Postcomment < ApplicationRecord
	belongs_to :user
	belongs_to :post

	validates :text, presence: true
	validates :text, length: { in: 4..256 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
 has_many :posts
 has_many :postcomments
 has_many :photos
 has_many :images
 has_many :votes

 validates :nickname, :email, :password_confirmation, :password, presence: true
 validates :nickname, :email, uniqueness: true

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/default.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/vote.rb
class Vote < ApplicationRecord
	belongs_to :user
	belongs_to :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :devise_sign_up_params, if: :devise_controller?
  protect_from_forgery with: :exception


  private

  def devise_sign_up_params
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :nickname, :avatar])
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_image, only: [:edit,:update,:destroy]
  def index
  	@images=Image.all
  end

  def new
  end

  def edit
  end

  def update
  end

  def destroy
    @image.destroy
    redirect_to images_path
  end

  def create
  	@user = current_user

  	if params[:images]
  		params[:images].each {|image| 
  		@files = @user.images.create(image: image)
  	}
  end
  redirect_to images_path
  end

  private

  def image_params
    params.require(:images).permit(:user_id, :image)
  end

def set_image
      @image = Image.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  @users = User.all	
  @posts = Post.all.order(created_at: :DESC)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_photo, only: [:edit,:update,:destroy]
  def index
    @photos = Photo.all
    @like = {}
    @photos.each do |photo|
      @votes = Vote.where(photo_id: photo.id).sum(:like)
        @like[photo.id] = @votes
  end

  end

  def new
    @photo = Photo.new
  end

  def create
   params[:photo][:category_id] = params[:category_id]
   params[:photo][:user_id] = current_user.id
   params[:photo][:photo] 
   @photo = Photo.create(photo_params)
    redirect_to photos_path
  end

  def edit
  end

  def update
  end

  def destroy
    @photo.destroy
    redirect_to photos_path
  end

  def vote
    @photo = Photo.find(params[:id])
    @vote = Vote.where(user_id: current_user.id, photo_id: @photo.id).first
    if @vote == nil 
        @like = 1
        Vote.create(user_id: current_user.id, photo_id: @photo.id, like: @like)
    else
      if @vote.like == 0
        @vote.update(like: @vote.like+1)
        else
            @vote.update(like: @vote.like-1)
        end
    end
    redirect_to photos_path
  end

private

  def photo_params
    params.require(:photo).permit(:user_id, :category_id, :name, :photo)
  end
  
  def set_photo
      @photo = Photo.find(params[:id])
    end
end

app/controllers/postcomments_controller.rb
class PostcommentsController < ApplicationController
	before_action :authenticate_user!

	def create
		params[:postcomment][:post_id] = params[:post_id]
		params[:postcomment][:user_id] = current_user.id
		@comment = Postcomment.create(postcomments_params)
  if @comment.save
    redirect_to post_path(params[:post_id])
  else 
    @comment.errors.full_messages.each do |msg|
     @msg = msg
    end  
    flash[:notice] = "#{@msg}"
    redirect_to post_path(params[:post_id])
  end
end

def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.postcomments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
private

	def postcomments_params
		params.require(:postcomment).permit(:user_id, :post_id, :text)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show,:edit,:update,:destroy]
  def new
  @post = Post.new
  end 

  def show
    @comments = Postcomment.where(post_id: @post.id)
  end

  def create
  	@post = current_user.posts.build(post_params)
  	if @post.save
  		redirect_to root_path
  	else
  		render 'new'
  	end

  end
  
  def destroy
  	@post.destroy
  	redirect_to root_path
  end

  def edit
  end

  def update
  	@post.update(post_params)
  	redirect_to root_path
  end

  private
  	def post_params
  		params.require(:post).permit(:user_id,:title,:body)
	
  	end

  	def set_post
  		@post = Post.find(params[:id])
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/postcomments_helper.rb
module PostcommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/images/_form.html.erb
<center><p><%= f.label "Upload Images" %><br>
<%= file_field_tag "images[]", type: :file, multiple: true %></p>
<br>
<p><%= f.submit "Upload" %></p></center>

app/views/images/index.html.erb
<style >
 #pd{
	margin-left: 15px;
	margin-right: 15px;
}
.silk a{
	text-decoration: none;
	color: grey;
}
</style>
<div class='silk'>
<center><%= link_to "New Photo", new_photo_path, class: "btn btn-default" %>
<%= link_to "New Multi Photo", new_image_path, class: "btn btn-default" %></center>
</div>
<br>
<% if @images == [] %>
<center><h1>Photo ninchen</h1></center>
	<% else %>
	<div class="container">
		<% @images.each do |image| %>
		<div class="col-lg-6">
			<p><div id="pd"><%= image_tag image.user.avatar.url(:thumb), width: 30, heigth: 30 %><%= image.user.nickname %></p>
					</div>	
			<p><%= image_tag(image.image.url) %></p>
			<% if current_user != nil and current_user.id == image.user_id %>
				<%= link_to "Edit",  edit_image_path(image.id) %> or
				<%= link_to "Delete", image_path(image.id), data: {confirm: 'Rili deleted your post?'}, method: :delete %>
			<%end%>
			<hr>
		</div>

		<% end %>
	</div>
<% end %>

app/views/images/new.html.erb
<center><%= form_for :images, url: images_path, html: { multipart: true } do |f| %>
	
	<%= render 'images/form', f:f%>
<%end%></center>

app/views/photos/_form.html.erb
	<p><%= f.label "Category: " %>  
	<%= select_tag 'category_id', options_from_collection_for_select(Category.all, 'id', 'name') %></p>

	<p><%= f.label :name %></p>
	 <%= f.text_field :name %><br />

    <p><%= f.label :photo %></p>
    <%= f.file_field :photo %><br />


  <p><%= f.submit "Save" %></p>

app/views/photos/edit.html.erb
<center><%= form_for @photo, url: photo_path, method: :patch do |f| %>
	<% if @photo.errors.any? %>
	 <% @pohoto.errors.full_messages.each do |msg| %>
	 	<li><%=msg%></li>
	   <%end%>
	 <%end%>
	<%= render 'photos/form', f:f%>
<%end%></center>

app/views/photos/index.html.erb
<style >
 #pd{
	margin-left: 15px;
	margin-right: 15px;
}
.silk a{
	text-decoration: none;
	color: grey;
}
</style>
<div class='silk'>
<center><%= link_to "New Photo", new_photo_path, class: "btn btn-default" %>
<%= link_to "New Multi Photo", new_image_path, class: "btn btn-default" %></center>
</div>
<% if @photos == [] %>
	<center><h1>Photo ninchen</h1></center>
	<% else %>
	<div class="container">
		<% @photos.each do |photo| %>
		<div class="col-lg-6">
		<p><div id="pd"><%= image_tag photo.user.avatar.url(:thumb), width: 30, heigth: 30 %><%= photo.user.nickname %></p>
		</div>	
		<p><%= image_tag(photo.photo_url) %></p>
		<p><%= photo.category.name %></p>
		<p><%= link_to vote_photo_path(photo.id) do %>
		<i class="glyphicon glyphicon-heart-empty"></i>
		<% end %>
		(<%= @like[photo.id] %>)</p>
		<% if current_user != nil and current_user.id == photo.user_id %>
						<%= link_to "Edit",  edit_photo_path(photo.id) %> or
						<%= link_to "Delete", photo_path(photo.id), data: {confirm: 'Rili deleted your post?'}, method: :delete %>
					<%end%>
		<hr>
		</div>
	<% end %>
	</div>
<% end %>	

app/views/photos/new.html.erb
<center><%= form_for @photo, url: photos_path do |f| %>
	<% if @photo.errors.any? %>
	 <% @pohoto.errors.full_messages.each do |msg| %>
	 	<li><%=msg%></li>
	   <%end%>
	 <%end%>
	<%= render 'photos/form', f:f%>
<%end%></center>

app/views/posts/_form.html.erb
  <p><%= f.label :title %></p>
  <%= f.text_field :title %><br />

  <p><%= f.label :body %></p>
	<%= f.text_area :body, :class => "tinymce", :rows => 40, :cols => 120 %>
  <%= tinymce %><br />
 
  <p><%= f.submit "Save" %></p>

app/views/posts/edit.html.erb
<center><%= form_for :post, url:post_path, method: :patch do |f| %>
	<% if @post.errors.any? %>
	 <% @post.errors.full_messages.each do |msg| %>
	 	<li><%=msg%></li>
	   <%end%>
	 <%end%>
<%= render 'posts/form', f:f%>
<%end%></center>

app/views/posts/new.html.erb
<center><%= form_for @post, url: posts_path, validate: true do |f| %>
	<% if @post.errors.any? %>
	 <% @post.errors.full_messages.each do |msg| %>
	 	<li><%=msg%></li>
	   <%end%>
	 <%end%>
	<%= render 'posts/form', f:f%>
<%end%></center>

app/views/posts/show.html.erb
<style>
.com { 
    text-align: center;
    padding: 20px;
}

.bord{
	background: #FFF8DC;
	border: 1px;
	border-style: solid;
	border-color: #DCDCDC;
	border-radius: 20px;
	margin-bottom: 5px;
	padding: 20px;
	margin-right: 15px;
	margin-left: 15px;
}

.ram
{
	margin-right: 15px;
	margin-left: 15px;
}

.time{
	text-align: right;
	opacity: 0.65;
}

.post{
	margin-left: 20px;
	margin-right: 20px;
}
</style>
<div class="post">
<div id="ed"><% if current_user != nil and current_user.id == 1 %>
				<%= link_to "Edit",  edit_post_path %> or
				<%= link_to "Delete", post_path, data: {confirm: 'Rili deleted your post?'}, method: :delete %>
			<%end%>
</div>
<h1><%= @post.title %></h1>
<p><%= sanitize @post.body %></p>
<hr>
</div>

<% @comments.each do |comment|%>
<div class="ram">
<p><%= image_tag comment.user.avatar.url(:thumb), width: 30, heigth: 30 %>
 User <b><%= comment.user.nickname %></b> write:</p>
 <div class = "bord">
<i><%= comment.text %></i>
</div>
<div class="time"><span class="glyphicon glyphicon-time"></span>
<small><%= comment.created_at %></small></div>
<%= link_to 'Destroy', [comment.post, comment], :confirm => 'Are you sure?', :method => :delete %>
</div>

<% end %>

	
<%= form_for :postcomment, url: post_postcomments_path(post_id: @post.id) do |f| %>
<% if flash[:notice] %>
  <div class="notice"> <%= flash[:notice] %> </div>
<% end %>
<div class="com">
	<p><%= f.label "Comment" %></p>
	<%= f.text_area :text,  class: "content-field", placeholder: "Add a comment"%><br />
 

 <p><%= f.submit "Send" %></p>
 </div>
<%end%>

	

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>